#!/bin/bash

#-------------------------------------------------------------------------------
# reinstall
#
# REINSTALLATION DE rEFInd 0.7.9
#
# ne fonctionne qu'avec la langue FR (fr_FR)
# Created by me for me
#
# Run this script after your first boot with archlinux-AAAA.MM.JJ-dual.iso (as root)

source `pwd`/ai-commons

# VARIABLES
IS_ESP_MOUNTED=0
STATUS_ESP_MOUNT=0
IS_NAME_ESP_EXISTE=0

NAME_PARTITION_ESP=""

CHEMIN_CONTENU_ESP=""

NAME_DIR_BOOT_MGR=""
NAME_BOOT_MGR=""

MOUNTPOINT_PARTITION_ESP="/mnt/boot/efi"

 
mount_efi_partition_if_not_mounted() {
    if [[ $IS_ESP_MOUNTED -eq 0 ]]; then
        mkdir -p ${MOUNTPOINT_PARTITION_ESP}
        if [[ $? -ne 0 ]]; then
            return 1
        fi
        mount -t vfat ${NAME_PARTITION_ESP} ${MOUNTPOINT_PARTITION_ESP}
        if [[ $? -ne 0 ]]; then
            return 1
        fi
        STATUS_ESP_MOUNT=1
    fi
}

check_and_return_name_partition_esp() {
    local esp=(`fdisk -l | awk '/EFI System/ {print $1}'`)
    if [[ "${esp}" != "" ]];then
        IS_NAME_ESP_EXISTE=1
        NAME_PARTITION_ESP=${esp}
#        echo "une partition ESP existe et est : "${NAME_PARTITION_ESP}
    else
        IS_NAME_ESP_EXISTE=0
#        echo "PAS de partition ESP !"
    fi
}
#
check_is_esp_mounted() {
    local part_esp=(`lsblk | awk '/\/boot\/efi/ {print $7}'`)
    if [[ "${part_esp}" != "" ]];then
        IS_ESP_MOUNTED=1
#        echo "La partition ESP est montée. "
    else
        IS_ESP_MOUNTED=0
#        echo "La partition ESP n'est PAS montée."
    fi
}

    #FINISH {{{
    finish() {
        print_title "RÉINSTALLATION DE rEFInd 0.7.9 TERMINÉE"
        print_info_finish "\n==> INFO : Fermer tous les terminaux ouverts ( TTY 2, ... )."
        pause_function       
        #umount mounted partitions
        if [[ $STATUS_ESP_MOUNT -eq 1 ]]; then
            umount -R ${MOUNTPOINT}
        fi
        # Si dans VirtualBox
        if [[ $IN_VIRTUAL_BOX -eq 1 ]]; then
            print_info_finish "\n==> INFO : Dans VirtualBox, éteindre le système, modifier ordre de démarrage dans Système,\n           enlever ISO dans Stokage et relancer la VM."
        else
            echo -e "\n"
        fi
        type_fins=("Redémarrer" "Éteindre");
        PS3="$prompt1"
        echo -e "Sélectionner l'arrêt ( Redémarrer ou Éteindre ) :"
        select OPT in "${type_fins[@]}"; do
            case "$REPLY" in
                1)
                    reboot
                    break
                    ;;
                2)
                    poweroff
                    break
                    ;;
                *)
                    invalid_option
                    ;;
            esac
        done
    }
    #}}}
#
# DÉBUT DU SCRIPT REINSTALL
#

print_title "RÉINSTALLATION DE rEFInd 0.7.9 SI EN UEFI"

# UEFI ou BIOS
check_is_uefi_or_bios
if [[ $IS_UEFI -eq 0 ]]; then
    print_warning "Installation en mode BIOS."
    print_warning "PAS de Réinstallation de rEFInd 0.7.9."
    pause_function
    exit 1
fi

# Installation dans VirtualBox ou réelle
check_is_in_virtualbox
if [[ $IN_VIRTUAL_BOX -eq 1 ]]; then
    NAME_DIR_BOOT_MGR="BOOT"
    NAME_BOOT_MGR="bootx64.efi"
    print_info_cyan "Installation dans Oracle VM VirtualBox."
else
    NAME_DIR_BOOT_MGR="refind"
    NAME_BOOT_MGR="refind_x64.efi"
    print_info_cyan "Installation réelle."
fi

# Sets the interval of inactivity
setterm -blank 0
#pause_function
#

check_and_return_name_partition_esp
if [[ $IS_NAME_ESP_EXISTE -eq 0 ]]; then
    print_warning "PAS de partition ESP !"
    print_warning "PAS de Réinstallation de rEFInd 0.7.9 !"
    pause_function
    exit 1
fi
#

check_is_esp_mounted
if [[ $IS_ESP_MOUNTED -eq 0 ]]; then
    CHEMIN_CONTENU_ESP="${MOUNTPOINT_PARTITION_ESP}/EFI"
    print_info_cyan "PAS de partition ESP montée !"
    print_info_cyan "A monter dans ${MOUNTPOINT_PARTITION_ESP}"
    print_info_cyan "Le chemin sera : "${CHEMIN_CONTENU_ESP}"/"${NAME_DIR_BOOT_MGR}
#    pause_function
else
    CHEMIN_CONTENU_ESP="/boot/efi/EFI"
    print_info_cyan "Partition ESP déjà montée !"
    print_info_cyan "Le chemin sera : "${CHEMIN_CONTENU_ESP}"/"${NAME_DIR_BOOT_MGR}
#    pause_function
fi
#

mount_efi_partition_if_not_mounted
if [[ $? -ne 0 ]]; then
    print_warning "Impossible de monter la partition ESP !"
    print_warning "PAS de Réinstallation de rEFInd 0.7.9 !"
    pause_function
    exit 1
fi
#

# TODO : MIS POUR VÉRIFICATIONS AVANT MODIFS
#print_info_cyan "Status si la partion ESP a été montée : STATUS_ESP_MOUNT = "$STATUS_ESP_MOUNT

# print_info_cyan "Contenu de la partion ESP :"
# ls ${CHEMIN_CONTENU_ESP}

print_info_cyan "AVANT MODIFICATIONS : Contenu du répertoire du Boot Manager qui sera modifié :"
ls -la ${CHEMIN_CONTENU_ESP}/${NAME_DIR_BOOT_MGR}

#pause_function
#

print_info_cyan "CONFIRMER LES MODIFICATIONS"
read_input_text "Confirmer la réinstallation de rEFInd 0.7.9"
if [[ $OPTION == n ]]; then
    print_info_finish "\n==> INFO : PAS de Réinstallation de rEFInd 0.7.9 !"
    #umount mounted partitions
    if [[ $STATUS_ESP_MOUNT -eq 1 ]]; then
        umount -R ${MOUNTPOINT}
    fi
    exit 0
fi


# Suppression rep icons (avec png)
print_info_cyan "Sauvegarde du répertoire << icons >> V 0.8.x dans : "${CHEMIN_CONTENU_ESP}/${NAME_DIR_BOOT_MGR}
cp -R ${CHEMIN_CONTENU_ESP}/${NAME_DIR_BOOT_MGR}/icons ${CHEMIN_CONTENU_ESP}/${NAME_DIR_BOOT_MGR}/icons.backup.v.0.8.x

print_info_cyan "Sauvegarde fichier refind.conf V 0.8.x dans : "${CHEMIN_CONTENU_ESP}/${NAME_DIR_BOOT_MGR}
cp -v ${CHEMIN_CONTENU_ESP}/${NAME_DIR_BOOT_MGR}/refind.conf ${CHEMIN_CONTENU_ESP}/${NAME_DIR_BOOT_MGR}/refind.conf.backup.v.0.8.x

print_info_cyan "Sauvegarde du manager de boot V 0.8.x dans : "${CHEMIN_CONTENU_ESP}/${NAME_DIR_BOOT_MGR}
cp -v ${CHEMIN_CONTENU_ESP}/${NAME_DIR_BOOT_MGR}/${NAME_BOOT_MGR} ${CHEMIN_CONTENU_ESP}/${NAME_DIR_BOOT_MGR}/${NAME_BOOT_MGR}.backup.v.0.8.x


# Copies du nouveau répertoire icons et des fichiers
print_info_cyan "Copie du répertoire << icons >> V 0.7.9 dans : "${CHEMIN_CONTENU_ESP}/${NAME_DIR_BOOT_MGR}
cp -R refind-efi-0.7.9/icons ${CHEMIN_CONTENU_ESP}/${NAME_DIR_BOOT_MGR}/icons

print_info_cyan "Copie des fichiers V 0.7.9 dans : "${CHEMIN_CONTENU_ESP}/${NAME_DIR_BOOT_MGR}
cp -v refind-efi-0.7.9/refind_x64.efi ${CHEMIN_CONTENU_ESP}/${NAME_DIR_BOOT_MGR}/${NAME_BOOT_MGR}

if [[ $IN_VIRTUAL_BOX -eq 1 ]]; then
    cp -v refind-efi-0.7.9/VBOX-refind.conf ${CHEMIN_CONTENU_ESP}/${NAME_DIR_BOOT_MGR}/refind.conf
else
    cp -v refind-efi-0.7.9/REEL-refind.conf ${CHEMIN_CONTENU_ESP}/${NAME_DIR_BOOT_MGR}/refind.conf
fi

# TODO : MIS POUR VÉRIFICATIONS APRES MODIFS
print_info_cyan "APRÈS MODIFICATIONS..."
print_info_cyan "Contenu du répertoire du Boot Manager modifié :"
ls -la ${CHEMIN_CONTENU_ESP}/${NAME_DIR_BOOT_MGR}
pause_function
#

# FIN
finish

exit 0
